name: fouda_pharma
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  fluent_ui: ^4.6.1
  fluentui_icons: ^1.0.0
  window_manager: ^0.3.2
  firebase_core: ^2.13.0
  firedart: ^0.9.2
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  riverpod_generator: ^2.1.4
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
