name: fouda_pharma
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  fluent_ui: ^4.6.1
  fluentui_icons: ^1.0.0
  window_manager: ^0.3.2
  shared_preferences: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  syncfusion_flutter_pdf: ^21.2.8
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  syncfusion_flutter_charts: ^21.2.10
  firebase_core: ^2.14.0
  system_theme: ^2.2.0
  nil: ^1.1.1
  smooth_page_indicator: ^1.1.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  url_launcher: ^6.1.11
  nimbostratus: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  riverpod_generator: ^2.1.4
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6
  flutter_lints: ^2.0.0
  freezed: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
