// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFkGjCDiIAJxZVTcNGToCrUGVJgV94Aw',
    appId: '1:228655808143:web:7d93af7de25a4f9a70bafa',
    messagingSenderId: '228655808143',
    projectId: 'fouda-pharma',
    authDomain: 'fouda-pharma.firebaseapp.com',
    storageBucket: 'fouda-pharma.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYL4z8RIp7I0yuz_b2cW-QpYj86pHgtk',
    appId: '1:228655808143:android:06babd63fa98cdd070bafa',
    messagingSenderId: '228655808143',
    projectId: 'fouda-pharma',
    storageBucket: 'fouda-pharma.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP_EyyyETGQ694ebISqSN0tneY2UxUe7A',
    appId: '1:228655808143:ios:44a1d64538f0572570bafa',
    messagingSenderId: '228655808143',
    projectId: 'fouda-pharma',
    storageBucket: 'fouda-pharma.appspot.com',
    iosClientId:
        '228655808143-1ckknhh3v9qf407aoj5ailjuvi8ab3qr.apps.googleusercontent.com',
    iosBundleId: 'com.fouda.foudaPharma.RunnerTests',
  );
}
